---
name: mirror-upstream-tags

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  discover:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tags: ${{ steps.tags.outputs.tags }}
      latest_tag: ${{ steps.tags.outputs.latest_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MIRROR_TOKEN }}
      - name: Configure git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - name: Determine tags to mirror
        id: tags
        env:
          GH_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          set -euo pipefail
          git remote add upstream https://github.com/nirs/vmnet-helper.git
          git fetch upstream --tags
          upstream_tags=$(git ls-remote --refs --tags upstream | \
            awk '{print $2}' | sed 's|refs/tags/||' | sort -V)
          origin_tags=$(git ls-remote --refs --tags origin 2>/dev/null | \
            awk '{print $2}' | sed 's|refs/tags/||' | sort -V)
          missing_tags=""
          for tag in $upstream_tags; do
            if ! echo "$origin_tags" | grep -q "^$tag$"; then
              missing_tags="$missing_tags $tag"
              git fetch upstream "refs/tags/$tag:refs/tags/$tag"
              git push origin "refs/tags/$tag:refs/tags/$tag"
              if gh release view "$tag" >/dev/null 2>&1; then
                echo "Release $tag already exists"
              else
                gh release create "$tag" -t "$tag" -n "Mirror of upstream release $tag"
              fi
            fi
          done
          tags_json=$(printf '%s\n' $missing_tags | \
            python -c 'import sys,json; print(json.dumps([t for t in sys.stdin.read().split() if t]))')
          echo "tags=$tags_json" >> $GITHUB_OUTPUT
          latest_tag=$(printf '%s\n' $upstream_tags | tail -n1)
          echo "latest tag is $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

