name: mirror-upstream-release

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

# Keep the built-in token minimal; we're using a PAT for writes.
permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (use PAT so pushes use PAT creds)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MIRROR_PAT }}
          persist-credentials: true

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Point origin to PAT (ensure pushes use the PAT)
        env:
          GH_PAT: ${{ secrets.MIRROR_PAT }}
        run: |
          git remote set-url origin "https://x-access-token:${GH_PAT}@github.com/minikube-machine/vmnet-helper.git"

      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/nirs/vmnet-helper.git
          git fetch upstream --tags
          # (Optional) also fetch branches
          git fetch upstream

      - name: Push missing tags
        run: |
          set -euo pipefail
          # List tags from upstream (in FETCH_HEAD / remote tags)
          git tag -l > /tmp/local-tags.txt
          # Ensure local tag list matches upstream
          git for-each-ref --format='%(refname:strip=2)' refs/tags > /tmp/local-tags.txt
          # Create any tags locally that only exist upstream
          while read -r t; do
            # if tag t doesn't exist locally, create it pointing to upstream tag object
            if ! git rev-parse -q --verify "refs/tags/$t" >/dev/null; then
              git tag "$t" "refs/remotes/upstream/tags/$t" 2>/dev/null || true
            fi
          done < <(git ls-remote --tags upstream | awk '{print $2}' | sed 's#refs/tags/##' | sed 's#\^\{\}##' | sort -u)

          # Push all tags (safe; already authenticated with PAT)
          git push --tags origin

      - name: (Optional) Mirror branches
        run: |
          # This mirrors upstream branches to origin (excluding PR refs)
          git push --prune origin "refs/remotes/upstream/*:refs/heads/*"
