name: mirror-upstream-tags
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.tags.outputs.tags }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Find missing tags
        id: tags
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tags=$(./missing-tags)
          echo "tags=$tags" >> $GITHUB_OUTPUT
  release:
    needs: discover
    if: needs.discover.outputs.tags != '[]'
    strategy:
      fail-fast: false
      matrix:
        tag: ${{ fromJson(needs.discover.outputs.tags) }}
        platform: [macos-15]
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write
    steps:
      - name: Checkout self source
        uses: actions/checkout@v4
      - name: Checkout upstream source
        uses: actions/checkout@v4
        with:
          repository: nirs/vmnet-helper
          ref: ${{ matrix.tag }}
          path: upstream
          fetch-depth: 1
      - name: Install requirements
        run: brew install meson diffoscope
      - name: Build
        working-directory: upstream
        run: ./build.sh build
      - name: Test reproducibility
        working-directory: upstream
        run: |
          ./build.sh repro
          diffoscope build/vmnet-helper.tar.gz repro/vmnet-helper.tar.gz
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # NOTE: We upload the tarball built from upstream code with our
        # install.sh, configured to install from this repo.
        run: |
          tag="${{ matrix.tag }}"
          gh release create "$tag" -t "$tag" -n "Mirror of upstream release $tag"
          gh release upload "$tag" upstream/build/vmnet-helper.tar.gz install.sh
