# SPDX-FileCopyrightText: The vmnet-helper authors
# SPDX-License-Identifier: Apache-2.0

---
name: Release

on:
    push:
        tags:
            - '*'
jobs:
  release:
    name: Release artifacts
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-13
          - macos-15
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write
    steps:
      - name: Checkout self source
        uses: actions/checkout@v4
      - name: Checkout upstream source
        uses: actions/checkout@v4
        with:
          repository: nirs/vmnet-helper
          ref: ${{ github.ref_name }}
          path: upstream
          fetch-depth: 1
      - name: Install requirements
        run: brew install meson diffoscope
      - name: Build
        run: |
          cd upstream
          meson setup build
          meson compile -C build
          ./archive.sh build
      - name: Test reproducibility
        run: |
          cd upstream
          meson setup repro
          meson compile -C repro
          ./archive.sh repro
          diffoscope build/vmnet-helper-*.tar.gz repro/vmnet-helper-*.tar.gz
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: upstream
        run: |
          gh release upload "${GITHUB_REF_NAME}" build/vmnet-helper-*.tar.gz --clobber
      - name: Upload artifact to release
        env:
          GH_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        working-directory: upstream
        run: |
          set -euo pipefail
          repo="minikube-machine/vmnet-helper"
          tag="${{ github.ref_name }}"
          tarball=$(./upstream/build/vmnet-helper-*.tar.gz)
          if ! gh release view "$tag" --repo "$repo" >/dev/null 2>&1; then
            gh release create "$tag" --repo "$repo" -t "$tag" -n "Mirror of upstream release github.com/nirs/vmnet-helper $tag "
          fi
          gh release upload --repo "$repo" "$tag" "$tarball" ./install.sh --clobber
